### ISSUE TITLE
Ошибка отправки невыбранного файла аватара

### ISSUE THREAD

**Issue by yuri25** [doroninds/Laravel-Social-network#10]
Если просто нажать отправить не выбрав файл - выдает ошибку 
`Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function store() on null`

`app/Http/Controllers/FileController.php`

```
$user = $this->user->auth();
        $request->file('image')->store('public/avatars/' . $user->id);
        $user->avatar = 'storage/avatars/' . $user->id . '/' . $request->file('image')->hashName();
```

**Comment by doroninds** [comment]
[Исправлено](https://github.com/doroninds/Laravel-Social-network/commit/b80262ddcad65913516955848de6a3b9c810a13b)
