### ISSUE TITLE
Ошибка при создании приватной группы

### ISSUE THREAD

**Issue by yuri25** [doroninds/Laravel-Social-network#11]
`ErrorException thrown with message "Trying to get property of non-object (View: /........./resources/views/group/show.blade.php)"`
`/storage/framework/views/3f9709298bbb1fe249c3133294bf35c4335cbe75.php`
Что то выделил эти строки....

`<?php $__env->startSection('heading', $group->name); ?>
<?php $__env->startSection('content'); ?>`

И ниже:
```
Arguments
"Trying to get property of non-object (View: /......./resources/views/group/show.blade.php)"
```

**Comment by doroninds** [comment]
[Исправлено](https://github.com/doroninds/Laravel-Social-network/commit/7eed4aa98795b2eb39d77e9e5e0ec223cb194050)
