### ISSUE TITLE
Не срабатывает переход по ссылкам логин и регистрация

### ISSUE THREAD

**Issue by yuri25** [doroninds/Laravel-Social-network#4]
В самом верху сайта две ссылки - вход и регистрация. По умолчанию при открытии сайта  открывается страница с логином, перейти на регистрацию можно при нажатии на кнопку внизу. Аналогично если нажал кнопку регистрация внизу то перейти на логин по верхней ссылке не получается. Я так думаю это никакой не косяк на данной стадии разработки. Установил, никаких особо глюков не обнаружил.  Кнопки лайков работают только на увеличение что плюс что минус, голосовать можно за себя сколько угодно.

**Comment by yuri25** [comment]
Новости, редактирование профиля, просмотр юзеров и добавление друзей я так понимаю все в разработке.

**Comment by yuri25** [comment]
При создании группы подписчиков почему то сразу 2, если я потом присоединяюсь к группе пользователя то их становится 3.... хотя нас всего 2 - админ и пользователь.

**Comment by doroninds** [comment]
Да, ссылки были не рабочие. Поправил. Новости и добавление другого функционала будет. Пока немного занят другим проектом. Расписание разработки/доработки обновлю. По группам - скорректирована миграция, изначально планировалось создавать группу с 1 подписчиком, в данном случае автор группы. Добавлен автора в группу будет реализован через метод создания группы. В остальном если будут пожелание, пожалуйста :)
