### ISSUE TITLE
Не загружается картинка в профиль

### ISSUE THREAD

**Issue by yuri25** [doroninds/Laravel-Social-network#6]
Выглядит это так
![image](https://user-images.githubusercontent.com/253228/40332925-a851583a-5d5e-11e8-91cf-12f62079bedc.png)

Потом если нажимаю загрузить то выдает такую ошибку
```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function store() on null
```

Жалуется в этом файле  app/Http/Controllers/FileController.php

```
$user = $this->user->auth();
        $request->file('image')->store('public/avatars/' . $user->id);
        $user->avatar = 'storage/avatars/' . $user->id . '/' . $request->file('image')->hashName();
```

**Comment by yuri25** [comment]
И еще непонятно что с кнопками....
![image](https://user-images.githubusercontent.com/253228/40333051-2d14a626-5d5f-11e8-9da2-a0fc672a9d34.png)

**Comment by doroninds** [comment]
Перед загрузкой файла необходимо добавить символическую ссылку на storage.
Для этого необходимо выполнить команду: **php artisan storage:link**
Эта комнда автоматически добавить символическую ссылку на ваш storage, где и хранятся аватары.

**Comment by doroninds** [comment]
[Шаблон скорректирован](https://github.com/doroninds/Laravel-Social-network/commit/56c8253eb12b3af61d9bbf1ce77c740413b56249)
