### ISSUE TITLE
Отсутствует аватар по умолчанию

### ISSUE THREAD

**Issue by yuri25** [doroninds/Laravel-Social-network#9]
Может это и не ошибка, но при регистрации пользователя не назначается (не создается) выглядит так: 
![image](https://user-images.githubusercontent.com/253228/40451546-95223f10-5ee7-11e8-98eb-9d92418582ba.png)

**Comment by doroninds** [comment]
[Исправлено](https://github.com/doroninds/Laravel-Social-network/commit/b80262ddcad65913516955848de6a3b9c810a13b)
